/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_coinicles_coiniclesnet_CoiniclesnetVPN */

#ifndef _Included_network_coinicles_coiniclesnet_CoiniclesnetVPN
#define _Included_network_coinicles_coiniclesnet_CoiniclesnetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_PacketSize(JNIEnv *, jclass);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_Alloc(JNIEnv *, jclass);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_ReadPkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_WritePkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_coinicles_coiniclesnet_CoiniclesnetVPN
   * Method:    SetInfo
   * Signature: (Lnetwork/coinicles/coiniclesnet/CoiniclesnetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_network_coinicles_coiniclesnet_CoiniclesnetVPN_SetInfo(JNIEnv *, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
