/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_coinicles_coiniclesnet_CoiniclesnetVPN_VPNInfo */

#ifndef _Included_network_coinicles_coiniclesnet_CoiniclesnetVPN_VPNInfo
#define _Included_network_coinicles_coiniclesnet_CoiniclesnetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
