#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/coiniclesnet || echo "failed to setcap coiniclesnet"
adduser --quiet --system --home /var/lib/coiniclesnet debian-coiniclesnet || echo "debian-coiniclesnet user not added"
