#!/bin/sh

PERMS_OWNER=root
PERMS_GROUP=admin
CHOWN=$PERMS_OWNER:$PERMS_GROUP

# set up coiniclesnet data dir
[ -e /var/lib/coiniclesnet/ ] || mkdir /var/lib/coiniclesnet 
chown $CHOWN /var/lib/coiniclesnet
chmod g+w /var/lib/coiniclesnet

# mv files copied into $INSTALL_PREFIX/extra/ to their proper locations
mv /opt/coiniclesnet/extra/coiniclesnet_macos_daemon_script.sh /var/lib/coiniclesnet
chown $CHOWN /var/lib/coiniclesnet/coiniclesnet_macos_daemon_script.sh
chmod 770 /var/lib/coiniclesnet/coiniclesnet_macos_daemon_script.sh

mv /opt/coiniclesnet/extra/network.coinicles.coiniclesnet.daemon.plist /Library/LaunchDaemons/
chown $CHOWN /Library/LaunchDaemons/network.coinicles.coiniclesnet.daemon.plist
chmod 640 /Library/LaunchDaemons/network.coinicles.coiniclesnet.daemon.plist

# clean up by removing 'extra/' (so long as it's empty)
rmdir /opt/coiniclesnet/extra/

# bootstrap
/opt/coiniclesnet/bin/coiniclesnet-bootstrap mainnet /var/lib/coiniclesnet/bootstrap.signed
chown $CHOWN /var/lib/coiniclesnet/bootstrap.signed

# generate configs
/opt/coiniclesnet/bin/coiniclesnet -g /var/lib/coiniclesnet/coiniclesnet.ini
chown $CHOWN /var/lib/coiniclesnet/coiniclesnet.ini

# register with launchd and start
launchctl load /Library/LaunchDaemons/network.coinicles.coiniclesnet.daemon.plist
launchctl start network.coinicles.coiniclesnet.daemon
